### ISSUE TITLE
Would Like to make a basic text document (json)

### ISSUE THREAD

**Issue by NeonSupernova** [mobibean/codesnack-ide-feature-requests#58]
I know I can make a json document after making a project folder, but their is no option to make a plain text document when making a new document, it asks you to select a template. All I am asking for is an option to create a plain text document

**Comment by bushev** [comment]
Hey @NeonSupernova,

Just to be sure, are you looking for a way to create a JSON file out of the project scope?

**Comment by NeonSupernova** [comment]
Yes, that is pretty much what Im asking, though, for functionality, just having an option for json there isn't really optimal, maybe have a dropdown menu for non-language file editing. Like json, csv, etc.

**Comment by bushev** [comment]
Got it! So, the main issue here is that the file can't exist outside a project. The top-level element in the app is a Project. A project has many files. In order to create a file, you have to create a project first. As an option, you can create just one project and place all your JSON files into that project. Will it work for you?

Regarding the non-code edition of some text files, the feature looks interesting. I've created a new feature request here: https://github.com/mobibean/codesnack-ide-feature-requests/issues/64, let's see how many likes it generate.
